Shopp/accounts/urls.py
from django.urls import path
from .views import (
    signup,
    activate_account,
    user_login,
    logout_view,
    edit_profile,
    resend_activation_email,
    OrderListView,
    OrderDetailView,
    UserDashboardView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    ForgetPasswordView,
    RecoverPasswordView,
    PasswordChangedView,
)


app_name = "accounts"

urlpatterns = [
    path(
        "activate/<str:uidb64>/<str:token>/", activate_account, name="activate_account"
    ),
    path("resend_activation/", resend_activation_email, name="resend_activation"),
    path("login/", user_login, name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", UserDashboardView.as_view(), name="user_dashboard"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path(
        "change_password/", CustomPasswordChangeView.as_view(), name="change_password"
    ),
    path(
        "password_change_done/",
        CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/<uuid:order_uuid>/", OrderDetailView.as_view(), name="order_detail"),
    path("forget_password/", ForgetPasswordView.as_view(), name="forget_password"),
    path(
        "recover_password/<str:uidb64>/<str:token>/",
        RecoverPasswordView.as_view(),
        name="recover_password",
    ),
    path(
        "forgoten_password_changed/",
        PasswordChangedView.as_view(),
        name="forgoten_password_changed",
    ),
]

Shopp/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Shopp/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("search/", views.search, name="search"),
    path("about/", views.about_view, name="about"),
    path("contact/", views.contact_us, name="contact"),
    path(
        "<uuid:product_uuid>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "category/<path:category_path>/",
        views.product_by_category_list,
        name="product_by_category_list",
    ),
]

Shopp/shopp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls", namespace="shop")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shopp/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True)
    zip_code = models.CharField(max_length=10, blank=True)
    is_active = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',  
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to.',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',  
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
    )
    
    # Fields required for authentication
    REQUIRED_FIELDS = ['email', 'password']
    USERNAME_FIELD = 'email'


    def __str__(self):
        return self.username
    
    def get_username(self):
        return self.email

    def set_password(self, raw_password):
        # Your password hashing logic here
        super().set_password(raw_password)

    def check_password(self, raw_password):
        # Your password checking logic here
        return super().check_password(raw_password)

Shopp/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from .models import CustomUser


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    email = forms.EmailField(
        max_length=254,
        help_text="Required. Enter a valid email address.",
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=255,
        required=False,
        help_text="Optional.",
        widget=forms.Textarea(
            attrs={"rows": 3, "cols": 65, "class": "text-area text-area--primary-style"}
        ),
    )
    zip_code = forms.CharField(
        max_length=10,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Required. Minimum 8 characters.",
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "address",
            "zip_code",
            "password1",
            "password2",
        ]


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        required=True,
    )


class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=255,
        required=False,
        help_text="Optional.",
        widget=forms.Textarea(
            attrs={"rows": 3, "cols": 65, "class": "text-area text-area--primary-style"}
        ),
    )
    zip_code = forms.CharField(
        max_length=10,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "phone_number", "address", "zip_code"]


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Required. Minimum 8 characters.",
    )
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["old_password"].label = "Old Password"
        self.fields["new_password1"].label = "New Password"
        self.fields["new_password2"].label = "Confirm New Password"


class PasswordResetForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        )
    )


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter your new password",
                "class": "input-text input-text--primary-style",
            }
        ),
    )
    new_password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm your new password",
                "class": "input-text input-text--primary-style",
            }
        ),
    )

Shopp/templates/accounts/edit_profile.html
{% extends 'shop/base.html' %}


{% block title %}
  My shop - Edit Profile
{% endblock %}


{% block content %}

<div class="app-content">
    <div class="u-s-p-y-60">
  
  
        <div class="section__content">
            <div class="container">
                <div class="breadcrumb">
                    <div class="breadcrumb__wrap">
                        <ul class="breadcrumb__list">
                            <li class="has-separator">
  
                                <a href="{% url 'shop:product_list' %}">Home</a>
                            </li>
                            <li class="has-separator">
  
                                <a href="{% url 'accounts:user_dashboard' %}">Dashboard</a>
                            </li>
                            <li class="is-marked">
  
                                <a href="{% url 'accounts:edit_profile' %}">Edit profile</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="u-s-p-b-60">
        <div class="section__intro u-s-m-b-60">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section__text-wrap">
                            <h1 class="section__heading u-c-secondary">Edit Your Profile</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section__content">
          <div class="container">
              <div class="row row--center">
                  <div class="col-lg-6 col-md-8 u-s-m-b-30">
                      <div class="l-f-o">
                          <div class="l-f-o__pad-box">
                            <h2>Edit Profile</h2>
                            <form method="post" action="{% url 'accounts:edit_profile' %}">
                                {% csrf_token %}
                                <div class="form-group u-s-p-y-15">
                                    <label class="u-s-p-y-20" for="id_old_password">first name:</label>
                                    <div class="your-custom-input-container">
                                      {{ form.first_name }}
                                      {% for error in form.first_name.errors %}
                                        <p style="color: red;" class="error-message">{{ error }}</p>
                                      {% endfor %}
                                    </div>
                                  </div>
                                  <div class="form-group u-s-p-y-15">
                                    <label class="u-s-p-y-20" for="id_old_password">last name:</label>
                                    <div class="your-custom-input-container">
                                      {{ form.last_name }}
                                      {% for error in form.last_name.errors %}
                                        <p style="color: red;" class="error-message">{{ error }}</p>
                                      {% endfor %}
                                    </div>
                                  </div>
                                  <div class="form-group u-s-p-y-15">
                                    <label class="u-s-p-y-20" for="id_old_password">phone number:</label>
                                    <div class="your-custom-input-container">
                                      {{ form.phone_number }}
                                      {% for error in form.phone_number.errors %}
                                        <p style="color: red;" class="error-message">{{ error }}</p>
                                      {% endfor %}
                                    </div>
                                  </div>
                                  <div class="form-group u-s-p-y-15">
                                    <label class="u-s-p-y-20" for="id_old_password">address:</label>
                                    <div class="your-custom-input-container">
                                      {{ form.address }}
                                      {% for error in form.address.errors %}
                                        <p style="color: red;" class="error-message">{{ error }}</p>
                                      {% endfor %}
                                    </div>
                                  </div>
                                  <div class="form-group u-s-p-y-15">
                                    <label class="u-s-p-y-20" for="id_old_password">zip code:</label>
                                    <div class="your-custom-input-container">
                                      {{ form.zip_code }}
                                      {% for error in form.zip_code.errors %}
                                        <p style="color: red;" class="error-message">{{ error }}</p>
                                      {% endfor %}
                                    </div>
                                  </div>
                                  <div class="form-group u-s-p-y-40">
                                    <div>
                                        <button class="btn btn--e-brand u-s-p-t-70" type="submit">Save Changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
{% endblock %}

Shopp/templates/accounts/login.html
{% extends 'shop/base.html' %}


{% block title %}
  My shop - Sign In
{% endblock %}


{% block content %}
<div class="app-content">
  <div class="u-s-p-y-60">


      <div class="section__content">
          <div class="container">
              <div class="breadcrumb">
                  <div class="breadcrumb__wrap">
                      <ul class="breadcrumb__list">
                          <li class="has-separator">

                              <a href="{% url 'shop:product_list' %}">Home</a>
                          </li>
                          <li class="is-marked">

                              <a href="{% url 'accounts:login' %}">Sign In</a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div class="u-s-p-b-60">
    <div class="section__intro u-s-m-b-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section__text-wrap">
                        <h1 class="section__heading u-c-secondary">SIGN IN</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section__content">
      <div class="container">
          <div class="row row--center">
              <div class="col-lg-6 col-md-8 u-s-m-b-30">
                  <div class="l-f-o">
                      <div class="l-f-o__pad-box">

                        <a href="{% url 'accounts:forget_password' %}" style="color: black;">Forgot password?</a>
                          {% if error_message %}
                            <p style="color: red;">{{ error_message }}</p>
                          {% endif %}
                          <form method="post" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            <div class="form-group u-s-p-y-15">
                              <label class="u-s-p-y-20" for="id_old_password">Enter your email</label>
                              <div class="your-custom-input-container">
                                {{ form.username }}
                                {% for error in form.username.errors %}
                                  <p style="color: red;" class="error-message">{{ error }}</p>
                                {% endfor %}
                              </div>
                            </div>
                            <div class="form-group u-s-p-y-15">
                              <label class="u-s-p-y-20" for="id_old_password">enter your password:</label>
                              <div class="your-custom-input-container">
                                {{ form.password }}
                                {% for error in form.password.errors %}
                                  <p style="color: red;" class="error-message">{{ error }}</p>
                                {% endfor %}
                              </div>
                            </div>
                            <div class="form-group u-s-p-y-40">
                              <div>
                                <button class="btn btn--e-brand u-s-p-t-70" type="submit">Sing In</button>
                              </div>
                            </div>
                          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Shopp/templates/accounts/user_dashboard.html
{% extends 'shop/base.html' %}

{% block title %}
  My shop - User Dashboard
{% endblock %}

{% block content %}


<div class="app-content">
  <div class="u-s-p-y-60">
    <div class="section__content">
        <div class="container">
            <div class="breadcrumb">
                <div class="breadcrumb__wrap">
                    <ul class="breadcrumb__list">
                        <li class="has-separator">

                            <a href="{% url "shop:product_list" %}">Home</a></li>
                        <li class="is-marked">

                            <a href="{% url "accounts:user_dashboard" %}">My Account</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
  </div>
  <div class="u-s-p-b-60">

    
    <div class="section__content">
        <div class="dash">
          <div class="container">
            <div class="row">
              {% if not user.is_active %}
              <div class="section__content">
                <div class="container">
                    <div class="row row--center">
                        <div class="col-lg-6 col-md-8 u-s-m-b-30">
                          <div class="l-f-o">
                            <div class="l-f-o__pad-box">
                              <p>Your account is not yet activated.</p>
                              <form method="post" action="{% url 'accounts:resend_activation' %}">
                                {% csrf_token %}
                                <div class="form-group u-s-p-y-40">
                                  <div>
                                    <button class="btn btn--e-brand u-s-p-t-70" type="submit">Resend Activation Email</button>
                                  </div>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
            {% endif %}
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            </div>
          </div>
        </div>
      </div>
    <div class="section__content">
        <div class="dash">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-12">

                      
                      <div class="dash__box dash__box--bg-white dash__box--shadow u-s-m-b-30">
                          <div class="dash__pad-1">
                              {% if user.is_authenticated %}
                                  <span class="dash__text u-s-m-b-16">Hello {{ user.first_name }} {{ user.last_name }} </span>
                              {% else %}
                                  <span class="dash__text u-s-m-b-16">Hello</span>
                              {% endif %}
                              <ul class="dash__f-list">
                                  <li>

                                      <a href="{% url 'accounts:order_list' %}">Orders</a>
                                  </li>
                                  <li>

                                      <a href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                                  </li>
                                  <li>

                                      <a href="{% url 'accounts:change_password' %}">Change Password</a>
                                  </li>
                              </ul>
                          </div>
                      </div>
                    </div>
                    <div class="col-lg-9 col-md-12">
                        <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white u-s-m-b-30">
                            <div class="dash__pad-2">
                                <h1 class="dash__h1 u-s-m-b-14">Manage My Account</h1>



                                <span class="dash__text u-s-m-b-30">From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.</span>
                                <div class="row">
                                    <div class="col-lg-6 u-s-m-b-30">
                                        <div class="dash__box dash__box--bg-grey dash__box--shadow-2 u-h-100">
                                            <div class="dash__pad-3">
                                                <h2 class="dash__h2 u-s-m-b-8">PERSONAL PROFILE</h2>
                                                <div class="dash__link dash__link--secondary u-s-m-b-8">

                                                    <a href="{% url 'accounts:edit_profile' %}">Edit</a></div>

                                                <span class="dash__text">{{ user.first_name }} {{ user.last_name }}</span>

                                                <span class="dash__text">{{ user.email }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 u-s-m-b-30">
                                        <div class="dash__box dash__box--bg-grey dash__box--shadow-2 u-h-100">
                                            <div class="dash__pad-3">
                                                <h2 class="dash__h2 u-s-m-b-8">ADDRESS BOOK</h2>

                                                <span class="dash__text-2 u-s-m-b-8">Default Shipping Address</span>
                                                <div class="dash__link dash__link--secondary u-s-m-b-8">

                                                    <a href="{% url 'accounts:edit_profile' %}">Edit</a></div>

                                                <span class="dash__text">{{ user.address }}</span>

                                                <span class="dash__text">(+0) {{ user.phone_number }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>




{% endblock %}