Shopp/accounts/urls.py
from django.urls import path
from .views import (
    signup,
    activate_account,
    user_login,
    logout_view,
    edit_profile,
    resend_activation_email,
    OrderListView,
    OrderDetailView,
    UserDashboardView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    ForgetPasswordView,
    RecoverPasswordView,
    PasswordChangedView,
)


app_name = "accounts"

urlpatterns = [
    path(
        "activate/<str:uidb64>/<str:token>/", activate_account, name="activate_account"
    ),
    path("resend_activation/", resend_activation_email, name="resend_activation"),
    path("login/", user_login, name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", UserDashboardView.as_view(), name="user_dashboard"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path(
        "change_password/", CustomPasswordChangeView.as_view(), name="change_password"
    ),
    path(
        "password_change_done/",
        CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/<uuid:order_uuid>/", OrderDetailView.as_view(), name="order_detail"),
    path("forget_password/", ForgetPasswordView.as_view(), name="forget_password"),
    path(
        "recover_password/<str:uidb64>/<str:token>/",
        RecoverPasswordView.as_view(),
        name="recover_password",
    ),
    path(
        "forgoten_password_changed/",
        PasswordChangedView.as_view(),
        name="forgoten_password_changed",
    ),
]

Shopp/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Shopp/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("search/", views.search, name="search"),
    path("about/", views.about_view, name="about"),
    path("contact/", views.contact_us, name="contact"),
    path(
        "<uuid:product_uuid>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "category/<path:category_path>/",
        views.product_by_category_list,
        name="product_by_category_list",
    ),
]

Shopp/shopp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls", namespace="shop")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shopp/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True)
    zip_code = models.CharField(max_length=10, blank=True)
    is_active = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',  
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to.',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',  
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
    )
    
    # Fields required for authentication
    REQUIRED_FIELDS = ['email', 'password']
    USERNAME_FIELD = 'email'


    def __str__(self):
        return self.username
    
    def get_username(self):
        return self.email

    def set_password(self, raw_password):
        # Your password hashing logic here
        super().set_password(raw_password)

    def check_password(self, raw_password):
        # Your password checking logic here
        return super().check_password(raw_password)

Shopp/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from .models import CustomUser


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    email = forms.EmailField(
        max_length=254,
        help_text="Required. Enter a valid email address.",
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=255,
        required=False,
        help_text="Optional.",
        widget=forms.Textarea(
            attrs={"rows": 3, "cols": 65, "class": "text-area text-area--primary-style"}
        ),
    )
    zip_code = forms.CharField(
        max_length=10,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Required. Minimum 8 characters.",
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "address",
            "zip_code",
            "password1",
            "password2",
        ]


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        required=True,
    )


class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=255,
        required=False,
        help_text="Optional.",
        widget=forms.Textarea(
            attrs={"rows": 3, "cols": 65, "class": "text-area text-area--primary-style"}
        ),
    )
    zip_code = forms.CharField(
        max_length=10,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "phone_number", "address", "zip_code"]


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Required. Minimum 8 characters.",
    )
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["old_password"].label = "Old Password"
        self.fields["new_password1"].label = "New Password"
        self.fields["new_password2"].label = "Confirm New Password"


class PasswordResetForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        )
    )


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter your new password",
                "class": "input-text input-text--primary-style",
            }
        ),
    )
    new_password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm your new password",
                "class": "input-text input-text--primary-style",
            }
        ),
    )

Shopp/templates/accounts/password/change_password.html
{% extends 'shop/base.html' %}



{% block title %}
  My shop - Change Password
{% endblock %}



{% block content %}
<div class="app-content">
  <div class="u-s-p-y-90">

    <div class="section__content">
      <div class="container">
          <div class="breadcrumb">
              <div class="breadcrumb__wrap">
                  <ul class="breadcrumb__list">
                      <li class="has-separator">

                          <a href="{% url 'shop:product_list' %}">Home</a>
                        </li>
                        <li class="has-separator">
                          <a href="{% url 'accounts:user_dashboard' %}">Dashboard</a>
                        </li>
                      <li class="is-marked">

                          <a href="{% url 'accounts:change_password' %}">Change Password</a>
                        </li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
</div>
<div class="u-s-p-b-60">
  <div class="section__intro u-s-m-b-60">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="section__text-wrap">
                      <h1 class="section__heading u-c-secondary">Change Password</h1>
                  </div>
              </div>
          </div>
      </div>
  </div>
<div class="row row--center">
  <div class="col-lg-6 col-md-8 u-s-m-b-30">
      <div class="l-f-o">
          <div class="l-f-o__pad-box">
                  <form method="post" class="pd-tab__rev-f2" action="{% url 'accounts:change_password' %}">
                    {% csrf_token %}
                    <div class="form-group">
                      <label class="u-s-p-y-20" for="id_old_password">Old Password:</label>
                      <div class="your-custom-input-container">
                        {{ form.old_password }}
                        {% for error in form.old_password.errors %}
                          <p style="color: red;" class="error-message">{{ error }}</p>
                        {% endfor %}
                      </div>
                    </div>
                  
                    <div class="form-group">
                      <label class="u-s-p-y-20" for="id_new_password1">New Password:</label>
                      <div class="your-custom-input-container">
                        {{ form.new_password1 }}
                        {% for error in form.new_password1.errors %}
                          <p style="color: red;" class="error-message">{{ error }}</p>
                        {% endfor %}
                      </div>
                    </div>
                  
                    <div class="form-group">
                      <label class="u-s-p-t-20 u-s-p-b-60" for="id_new_password2">Confirm New Password:</label>
                      <div class="your-custom-input-container">
                        {{ form.new_password2 }}
                        {% for error in form.new_password2.errors %}
                          <p style="color: red;" class="error-message">{{ error }}</p>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="form-group u-s-p-y-40">
                      <div>
                        <button class="btn btn--e-brand u-s-p-t-70" type="submit">Change Password</button>
                      </div>
                    </div>
                  </form>
                </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}

Shopp/templates/accounts/password/password_change_done.html
{% extends 'shop/base.html' %}


{% block title %}
  My shop - Change Password Done
{% endblock %}


{% block content %}
<div class="app-content">
  <div class="u-s-p-y-90">
    <div class="container">
      <h2>Password Change Successful</h2>
      <span class="manage-o__text-2 u-c-silver"><p>Your password has been changed successfully.</p></span>
    </div>
  </div>
</div>
{% endblock %}

Shopp/templates/accounts/password/password_forget.html
{% extends 'shop/base.html' %}


{% block title %}
  My shop - Reset Password
{% endblock %}


{% block content %}
<div class="app-content">
  <div class="u-s-p-y-90">
    <div class="section__content">
      <div class="container">
          <div class="breadcrumb">
              <div class="breadcrumb__wrap">
                  <ul class="breadcrumb__list">
                      <li class="has-separator">

                          <a href="{% url 'shop:product_list' %}">Home</a>
                        </li>
                      <li class="is-marked">

                          <a href="{% url 'accounts:forget_password' %}">Reset Password</a>
                        </li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
  <div class="u-s-p-b-60">
    <div class="section__intro u-s-m-b-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section__text-wrap">
                        <h1 class="section__heading u-c-secondary">RESET PASSWORD</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section__content">
      <div class="container">
          <div class="row row--center">
              <div class="col-lg-6 col-md-8 u-s-m-b-30">
                  <div class="l-f-o">
                      <div class="l-f-o__pad-box">
                        <form method="post" class="pd-tab__rev-f2" action={% url "accounts:forget_password" %}>
                          {% csrf_token %}
                          <div class="form-group">
                            <label class="u-s-p-y-20" for="email">email:</label>
                            <div class="your-custom-input-container">
                              {{ form.email }}
                              {% for error in form.email.errors %}
                                      <p style="color: red;" class="error-message">{{ error }}</p>
                              {% endfor %}
                            </div>
                          </div>
                          <div class="form-group u-s-p-y-40">
                            <div>
                              <button class="btn btn--e-brand u-s-p-t-70" type="submit">Reset Password</button>
                            </div>
                          </div>
                        </form>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %}

Shopp/templates/accounts/password/password_reset.html
{% extends 'shop/base.html' %}


{% block title %}
  My shop - Reset Password
{% endblock %}

{% block content %}
<div class="app-content">
  <div class="u-s-p-y-60">


      <div class="section__content">
          <div class="container">
              <div class="breadcrumb">
                  <div class="breadcrumb__wrap">
                      <ul class="breadcrumb__list">
                          <li class="has-separator">

                              <a href="{% url 'shop:product_list' %}">Home</a>
                          </li>
                          <li class="is-marked">

                              <a href="{% url 'accounts:recover_password' %}">Recover Password</a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div class="u-s-p-b-60">
    <div class="section__intro u-s-m-b-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section__text-wrap">
                        <h1 class="section__heading u-c-secondary">CREATE AN ACCOUNT</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section__content">
      <div class="container">
          <div class="row row--center">
              <div class="col-lg-6 col-md-8 u-s-m-b-30">
                  <div class="l-f-o">
                      <div class="l-f-o__pad-box">
                          <h1 class="gl-h1">PERSONAL INFORMATION</h1>
                              <form method="post" class="pd-tab__rev-f2">
                                {% csrf_token %}
                                <div class="form-group">
                                  <label class="u-s-p-y-40" for="id_new_password1">New Password:</label>
                                  <div class="your-custom-input-container">
                                    {{ form.new_password1 }}
                                    {% for error in form.new_password1.errors %}
                                      <p style="color: red;" class="error-message">{{ error }}</p>
                                    {% endfor %}
                                  </div>
                                </div>
                              
                                <div class="form-group u-s-p-t-20 u-s-p-b-60">
                                  <label class="u-s-p-t-40 u-s-p-b-60" for="id_new_password2">Confirm New Password:</label>
                                  <div class="your-custom-input-container">
                                    {{ form.new_password2 }}
                                    {% for error in form.new_password2.errors %}
                                      <p style="color: red;" class="error-message">{{ error }}</p>
                                    {% endfor %}
                                  </div>
                                </div>
                                <div class="form-group">
                                  <div class="u-s-p-t-70">
                                    <button class="btn btn--e-brand u-s-p-t-70" type="submit">Reset Password</button>
                                  </div>
                                </div>
                              </form>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %}

Shopp/templates/accounts/password/password_reset_done.html
{% extends 'shop/base.html' %}

{% block title %}
  My shop - Change Password Done
{% endblock %}

{% block content %}
<div class="app-content">
  <div class="u-s-p-y-90">
    <div class="container">
      <h2>Your password changed</h2>
      <p>your password changed, you can login with new password.</p>
    </div>
  </div>
</div>
{% endblock %}

Shopp/templates/accounts/password/password_reset_email.html
{% extends 'shop/base.html' %}


{% block title %}
  My shop - Reset Password
{% endblock %}


{% block content %}
<div class="app-content">
  <div class="u-s-p-y-90">
    <div class="container">
        <h2>Reset Email Sent</h2>
        {% if email_sent %}
          <p>We've sent a email to you. Please check your inbox and click on the reset link to reset your password.</p>
        {% else %}
          <p>Something went wrong with sending the reset email. Please try again.</p>
        {% endif %}
    </div>
  </div>
</div>

{% endblock %}