Shopp/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Shopp/orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = "orders"

urlpatterns = [
    path(_("create/"), views.order_create, name="order_create"),
    path(
        "admin/order/<int:order_id>/",
        views.admin_order_detail,
        name="admin_order_detail",
    ),
    path(
        "admin/order/<int:order_id>/pdf/", views.admin_order_pdf, name="admin_order_pdf"
    ),
]

Shopp/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("search/", views.search, name="search"),
    path("about/", views.about_view, name="about"),
    path("contact/", views.contact_us, name="contact"),
    path(
        "<uuid:product_uuid>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "category/<path:category_path>/",
        views.product_by_category_list,
        name="product_by_category_list",
    ),
]

Shopp/shopp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls", namespace="shop")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shopp/orders/models.py
from coupons.models import Coupon
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.crypto import get_random_string
from django.db import models
import uuid
from shop.models import Product
from accounts.models import CustomUser


class Order(models.Model):
    # i want to save orders history, even if user removed.
    user = models.ForeignKey(
        CustomUser, blank=True, null=True, on_delete=models.SET_NULL
    )
    first_name = models.CharField("first name", max_length=50)
    last_name = models.CharField("last name", max_length=50)
    email = models.EmailField("e-mail")
    address = models.CharField("address", max_length=250)
    postal_code = models.CharField("postal code", max_length=20)
    city = models.CharField("city", max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    coupon = models.ForeignKey(
        Coupon, related_name="orders", null=True, blank=True, on_delete=models.SET_NULL
    )
    discount = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100)]
    )

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100))

    def generate_order_number(self):
        # Get the first 4 characters of the UUID
        uuid_prefix = str(self.uuid)[:4]

        # Format the created date as YYYYMMDD
        date_suffix = self.created.strftime("%Y%m%d")

        # Remove the decimal point from the price and convert to string
        price_without_decimal = str(self.get_total_cost()).replace(".", "")

        # Create the order number by combining the elements
        order_number = f"{uuid_prefix}-{price_without_decimal}-{date_suffix}"

        return order_number


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

Shopp/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from .models import CustomUser


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    email = forms.EmailField(
        max_length=254,
        help_text="Required. Enter a valid email address.",
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=255,
        required=False,
        help_text="Optional.",
        widget=forms.Textarea(
            attrs={"rows": 3, "cols": 65, "class": "text-area text-area--primary-style"}
        ),
    )
    zip_code = forms.CharField(
        max_length=10,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Required. Minimum 8 characters.",
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "address",
            "zip_code",
            "password1",
            "password2",
        ]


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        required=True,
    )


class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=255,
        required=False,
        help_text="Optional.",
        widget=forms.Textarea(
            attrs={"rows": 3, "cols": 65, "class": "text-area text-area--primary-style"}
        ),
    )
    zip_code = forms.CharField(
        max_length=10,
        required=False,
        help_text="Optional.",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "phone_number", "address", "zip_code"]


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Required. Minimum 8 characters.",
    )
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["old_password"].label = "Old Password"
        self.fields["new_password1"].label = "New Password"
        self.fields["new_password2"].label = "Confirm New Password"


class PasswordResetForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        )
    )


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter your new password",
                "class": "input-text input-text--primary-style",
            }
        ),
    )
    new_password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm your new password",
                "class": "input-text input-text--primary-style",
            }
        ),
    )

Shopp/orders/forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import Order


class OrderCreateForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    last_name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    email = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.EmailInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    address = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.Textarea(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    postal_code = forms.CharField(
        max_length=10,
        validators=[RegexValidator(r"^\d{10}$", "Enter a valid Iranian postal code.")],
        label="Postal Code",
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )
    city = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"size": "30", "class": "input-text input-text--primary-style"}
        ),
    )

    class Meta:
        model = Order
        fields = ["first_name", "last_name", "email", "address", "postal_code", "city"]

Shopp/orders/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db import transaction
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import render_to_string
import weasyprint

from cart.cart import Cart
from .forms import OrderCreateForm
from .models import Order
from .models import OrderItem


def send_order_notification(order_id):
    """
    Sends an e-mail notification when an order is successfully created.
    """
    order = Order.objects.get(id=order_id)
    subject = f"Order nr. {order.id}"
    message = f"Dear {order.first_name},\n\n" f"You have successfully placed an order."
    mail_sent = send_mail(
        subject, message, "admin@myshop.com", [order.email]
    )  # should be edited!!
    return mail_sent


@login_required
@transaction.atomic
def order_create(request):
    cart = Cart(request)
    # Check if the user's account is active
    if not request.user.is_active:
        return HttpResponseForbidden(
            "Your account is not active. Please contact support."
        )

    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            # Set the 'user' field to the currently logged-in user
            order.user = request.user
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            # clear the cart
            cart.clear()
            # send order notification
            send_order_notification(order.id)
            # set the order in the session
            request.session["order_id"] = order.id

            return redirect("accounts:user_dashboard")
    else:
        form = OrderCreateForm()
    return render(request, "orders/order/create.html", {"cart": cart, "form": form})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "admin/orders/order/detail.html", {"order": order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string("orders/order/pdf.html", {"order": order})
    response = HttpResponse(content_type="application/pdf")  # Common MIME types
    response[
        "Content-Disposition"
    ] = f"filename=order_{order.generate_order_number()}.pdf"
    weasyprint.HTML(string=html).write_pdf(
        response,
        stylesheets=[
            weasyprint.CSS(str(settings.BASE_DIR) + "/staticfiles/css/pdf.css")
        ],
    )
    return response

Shopp/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
 My shop - Checkout
{% endblock %}
{% block content %}
<div class="app-content">
    <div class="u-s-p-y-60">
  
  
        <div class="section__content">
            <div class="container">
                <div class="breadcrumb">
                    <div class="breadcrumb__wrap">
                        <ul class="breadcrumb__list">
                            <li class="has-separator">
  
                                <a href="{% url 'shop:product_list' %}">Home</a>
                            </li>
                            <li class="has-separator">
  
                                <a href="{% url 'cart:cart_detail' %}">Cart</a></li>
                            </li>
                            <li class="is-marked">
  
                                <a href="{% url "orders:order_create" %}">Check Out</a></li>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="u-s-p-b-60">
        <div class="section__intro u-s-m-b-60">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section__text-wrap">
                            <h1 class="section__heading u-c-secondary">{% trans "Checkout" %}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section__content">
            <div class="container">
                <div class="row row--center">
                    <div class="col-12 u-s-m-b-30">
                        <div class="table-responsive">
                            <table class="table-p">
                                <h1 class="gl-h1">{% trans "Your order" %}</h1>
                                <tr>
                                    <th>Product Name</th>
                                    <th>Price price</th>
                                    <th>Coupons</th>

                                 </tr>
                                {% for item in cart %}
                                {% with product=item.product %}
                                <tr>
                                    <td>
                                        <div class="table-p__box">
                                            <div class="table-p__img-wrap">
                                              <a href="{{ product.get_absolute_url }}">
                                                <img class="u-img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                              </a>
                                            </div>
                                            <div class="table-p__info">

                                                <span class="table-p__name">

                                                    <a href="product-detail.html">{{ product.name }}</a></span>

                                                <span class="table-p__category">

                                                    <a href="shop-side-version-2.html">{{ product.category.name }}</a></span>
                                                <ul class="table-p__variant-list">
                                                </ul>
                                            </div>
                                        </div>
                                    </td>
                                    <td>

                                        <span class="table-p__price">{{ item.quantity }} x {{ product.name }}</span>
                                        <span class="table-p__price">${{ item.total_price|floatformat:2 }}</span>
                                    </td>
                                    <td>

                                        {% if cart.coupon %}
                                            <span>
                                                {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                                                    "{{ code }}" ({{ discount }} % off)
                                                {% endblocktrans %}
                                                {% trans "Total" %}: ${{ cart.get_total_price_after_discount|floatformat:2 }}
                                            </span>
                                            <span class="">- ${{ cart.get_discount|floatformat:2 }}</span>
                                        {% else %}
                                                <span class="">there is not coupons</span>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endwith %}
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <div class="col-12 u-s-m-b-30">
                        <div class="l-f-o">
                            <div class="l-f-o__pad-box">
                                <form method="POST" class="l-f-o__form" >
                                    {% csrf_token %}
                                    <div class="form-group u-s-p-y-15">
                                        <label class="u-s-p-y-20" for="id_old_password">first name:</label>
                                        <div class="your-custom-input-container">
                                          {{ form.first_name }}
                                          {% for error in form.first_name.errors %}
                                            <p style="color: red;" class="error-message">{{ error }}</p>
                                          {% endfor %}
                                        </div>
                                      </div>
                                    <div class="form-group u-s-p-y-15">
                                        <label class="u-s-p-y-20" for="id_old_password">last name:</label>
                                        <div class="your-custom-input-container">
                                          {{ form.last_name }}
                                          {% for error in form.last_name.errors %}
                                            <p style="color: red;" class="error-message">{{ error }}</p>
                                          {% endfor %}
                                        </div>
                                      </div>
                                    <div class="form-group u-s-p-y-15">
                                        <label class="u-s-p-y-20" for="id_old_password">eamil:</label>
                                        <div class="your-custom-input-container">
                                          {{ form.email }}
                                          {% for error in form.email.errors %}
                                            <p style="color: red;" class="error-message">{{ error }}</p>
                                          {% endfor %}
                                        </div>
                                      </div>
                                    <div class="form-group u-s-p-y-15">
                                        <label class="u-s-p-y-20" for="id_old_password">address:</label>
                                        <div class="your-custom-input-container">
                                          {{ form.address }}
                                          {% for error in form.address.errors %}
                                            <p style="color: red;" class="error-message">{{ error }}</p>
                                          {% endfor %}
                                        </div>
                                      </div>
                                    <div class="form-group u-s-p-y-15">
                                        <label class="u-s-p-y-20" for="id_old_password">postal code:</label>
                                        <div class="your-custom-input-container">
                                          {{ form.postal_code }}
                                          {% for error in form.postal_code.errors %}
                                            <p style="color: red;" class="error-message">{{ error }}</p>
                                          {% endfor %}
                                        </div>
                                      </div>
                                    <div class="form-group u-s-p-y-15">
                                        <label class="u-s-p-y-20" for="id_old_password">city:</label>
                                        <div class="your-custom-input-container">
                                          {{ form.city }}
                                          {% for error in form.city.errors %}
                                            <p style="color: red;" class="error-message">{{ error }}</p>
                                          {% endfor %}
                                        </div>
                                      </div>
                                    
                                      <div class="form-group u-s-p-y-40">
                                        <div>
                                          <button class="btn btn--e-brand u-s-p-t-70" type="submit">Place Order</button>
                                        </div>
                                      </div>
                                </form>

                            </div>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
        </div>
    </div>
    </div>


{% endblock %}

Shopp/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}
Thank you
{% endblock %}
{% block content %}
<div class="app-content">
    <div class="u-s-p-y-60">
      <div class="container">
            <h1>Thank you</h1>
            <p>Your order has been successfully completed. Your order number is
            <strong>{{ order.generate_order_number }}</strong>.</p>
        </div>
    </div>
</div>
{% endblock %}

Shopp/templates/orders/order/pdf.html
{% load static %}
<html>
    <head> 
    </head>
<body>
<h1>My Shop</h1>
    <p>
        Invoice no. {{ order.generate_order_number }}</br>
        <span style="font-size:14px;">
            {{ order.created|date:"M d, Y" }}
        </span>
    </p>
    <h3>Bill to</h3>
    <p>
        {{ order.first_name }} {{ order.last_name }}<br>
        {{ order.email }}<br>
        {{ order.address }}<br>
        {{ order.postal_code }}, {{ order.city }}
    </p>
    <h3>Items bought</h3>
    <table>
        <thead>
        <tr >
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Cost</th>
        </tr>
        </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.product.name }}</td>
            <td class="num">${{ item.price }}</td>
            <td class="num">{{ item.quantity }}</td>
            <td class="num">${{ item.get_cost }}</td>
        </tr>
        {% endfor %}
        <tr class="total">
            <td colspan="3">Total</td>
            <td class="num">${{ order.get_total_cost }}</td>
        </tr>
    </tbody>
    </table>
    <span>
    {% if order.paid %}Paid{% else %}Not Paid yet{% endif %}
    </span>
</body>
</html>