Shopp/accounts/urls.py
from django.urls import path
from .views import (
    signup,
    activate_account,
    user_login,
    logout_view,
    edit_profile,
    resend_activation_email,
    OrderListView,
    OrderDetailView,
    UserDashboardView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    ForgetPasswordView,
    RecoverPasswordView,
    PasswordChangedView,
)


app_name = "accounts"

urlpatterns = [
    path(
        "activate/<str:uidb64>/<str:token>/", activate_account, name="activate_account"
    ),
    path("resend_activation/", resend_activation_email, name="resend_activation"),
    path("login/", user_login, name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", UserDashboardView.as_view(), name="user_dashboard"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path(
        "change_password/", CustomPasswordChangeView.as_view(), name="change_password"
    ),
    path(
        "password_change_done/",
        CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/<uuid:order_uuid>/", OrderDetailView.as_view(), name="order_detail"),
    path("forget_password/", ForgetPasswordView.as_view(), name="forget_password"),
    path(
        "recover_password/<str:uidb64>/<str:token>/",
        RecoverPasswordView.as_view(),
        name="recover_password",
    ),
    path(
        "forgoten_password_changed/",
        PasswordChangedView.as_view(),
        name="forgoten_password_changed",
    ),
]

Shopp/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Shopp/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("search/", views.search, name="search"),
    path("about/", views.about_view, name="about"),
    path("contact/", views.contact_us, name="contact"),
    path(
        "<uuid:product_uuid>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "category/<path:category_path>/",
        views.product_by_category_list,
        name="product_by_category_list",
    ),
]

Shopp/shopp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls", namespace="shop")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shopp/shop/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Slider, ProductComment, Product, Contact


class SliderAdminForm(forms.ModelForm):
    type = forms.ChoiceField(choices=Slider.TYPE_CHOICES)
    description = forms.CharField(
        widget=TinyMCE(
            attrs={"cols": 30, "rows": 30},
            mce_attrs={
                "plugins": "a11ychecker advcode advlist advtable anchor autocorrect autolink autoresize autosave casechange charmap checklist code codesample directionality editimage emoticons export footnotes formatpainter fullscreen help image importcss inlinecss insertdatetime link linkchecker lists media mediaembed mentions mergetags nonbreaking pagebreak pageembed permanentpen powerpaste preview quickbars save searchreplace table tableofcontents template tinycomments tinydrive tinymcespellchecker typography visualblocks visualchars wordcount",
                "theme": "silver",
                "toolbar_mode": "floating",
                "menubar": "file edit view insert format tools table help",
            },
        )
    )

    class Meta:
        model = Slider
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].required = False
        self.fields["product"].required = False

    def clean(self):
        cleaned_data = super().clean()
        type = cleaned_data.get("type")
        if type == "category":
            if not cleaned_data.get("category"):
                self.add_error("category", "Category is required for this type.")
        elif type == "product" or type == "banner":
            if not cleaned_data.get("product"):
                self.add_error("product", "Product is required for this type.")


class ProductCommentForm(forms.ModelForm):
    text = forms.CharField(
        label="YOUR REVIEW *",
        widget=forms.Textarea(attrs={"class": "text-area text-area--primary-style"}),
    )
    name = forms.CharField(
        label="NAME *",
        widget=forms.TextInput(attrs={"class": "input-text input-text--primary-style"}),
        required=False,
    )
    email = forms.EmailField(
        label="EMAIL *",
        widget=forms.TextInput(attrs={"class": "input-text input-text--primary-style"}),
    )

    class Meta:
        model = ProductComment
        fields = ["text", "name", "email"]


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        widgets = {
            "description": TinyMCE(
                attrs={"cols": 80, "rows": 10},
                mce_attrs={
                    "plugins": "a11ychecker advcode advlist advtable anchor autocorrect autolink autoresize autosave casechange charmap checklist code codesample directionality editimage emoticons export footnotes formatpainter fullscreen help image importcss inlinecss insertdatetime link linkchecker lists media mediaembed mentions mergetags nonbreaking pagebreak pageembed permanentpen powerpaste preview quickbars save searchreplace table tableofcontents template tinycomments tinydrive tinymcespellchecker typography visualblocks visualchars wordcount",
                    "theme": "silver",
                    "toolbar_mode": "floating",
                    "menubar": "file edit view insert format tools table help",
                },
            ),
        }


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-text input-text--border-radius input-text--primary-style",
                "placeholder": "name (reqired)",
                "id": "c-name",
            }
        ),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "input-text input-text--border-radius input-text--primary-style",
                "placeholder": "email (reqired)",
                "id": "c-email",
            }
        ),
    )
    subject = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-text input-text--border-radius input-text--primary-style",
                "placeholder": "subject (reqired)",
                "id": "c-subject",
            }
        ),
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "text-area text-area--primary-style",
                "placeholder": "your message (reqired)",
                "id": "c-message",
            }
        ),
    )

    class Meta:
        model = Contact
        fields = ["name", "email", "subject", "message"]

Shopp/shop/views.py
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, JsonResponse
from django.db.models import Q
from django.template.loader import render_to_string
from django.utils.html import escape
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, get_object_or_404, redirect
import pytz
from uuid import UUID

from cart.forms import CartAddProductForm
from .forms import ProductCommentForm, ContactForm
from .models import Category, Product, ProductImage, Slider, ProductComment


def paginate_data(data, request, items_per_page):
    page = request.GET.get("page", 1)
    paginator = Paginator(data, items_per_page)
    try:
        paginated_data = paginator.page(page)
    except PageNotAnInteger:
        paginated_data = paginator.page(1)
    except EmptyPage:
        paginated_data = paginator.page(paginator.num_pages)
    return paginated_data


def product_list(request):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by("-updated")[:16]

    # get slider
    sliders = Slider.objects.all()
    latest_banner = Slider.objects.filter(type="banner").order_by("-id").first()
    latest_category_banners = Slider.objects.filter(type="banner2").order_by("-id")[:3]
    # get latest discounts
    discounted_products = Product.objects.filter(
        Q(
            discount_start_date__lte=datetime.datetime.now(pytz.utc),
            discount_end_date__gte=datetime.datetime.now(pytz.utc),
        ),
        ~Q(discount_type="none"),
    ).order_by("-discount_type", "-discount_start_date")[:4]

    return render(
        request,
        "shop/product/index.html",
        {
            "category": category,
            "categories": categories,
            "sliders": sliders,
            "latest_banner": latest_banner,
            "latest_category_banners": latest_category_banners,
            "products": products,
            "discounted_products": discounted_products,
        },
    )


def product_by_category_list(request, category_path=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by("-updated")

    # handle category pages
    if not category_path or not category_path == "all":
        category_slugs = category_path.split("/")
        category = get_object_or_404(Category, slug=category_slugs[-1])
        # Include products of subcategories
        subcategories = Category.objects.filter(
            Q(id=category.id) | Q(parent_category=category.id)
        )
        products = products.filter(category__in=subcategories)

    paginated_products = paginate_data(products, request, 12)
    number_of_products = products.count()

    return render(
        request,
        "shop/product/category_list.html",
        {
            "category": category,
            "categories": categories,
            "products": paginated_products,
            "number_of_products": number_of_products,
        },
    )


def product_detail(request, product_uuid, product_slug):
    product = get_object_or_404(
        Product, uuid=product_uuid, slug=product_slug, available=True
    )
    comments = product.comments.all()
    cart_product_form = CartAddProductForm()
    category = product.category
    specifications = product.specifications.all()
    images = ProductImage.objects.filter(product=product)

    if request.method == "POST":
        if request.user.is_authenticated:
            comment_form = ProductCommentForm(request.POST)
            if comment_form.is_valid():
                # Check if the same data has been submitted recently
                if not ProductComment.objects.filter(
                    product=product,
                    user=request.user,
                    text=comment_form.cleaned_data["text"],
                    name=comment_form.cleaned_data["name"],
                    email=comment_form.cleaned_data["email"],
                ).exists():
                    comment = comment_form.save(commit=False)
                    comment.product = product
                    comment.user = request.user
                    comment.save()
        else:
            # Duplicate submission, redirect to avoid form resubmission
            return redirect(
                "shop:product_detail",
                product_uuid=product_uuid,
                product_slug=product_slug,
            )
    else:
        comment_form = ProductCommentForm()

    if request.headers.get("X-Requested-With") == "XMLHttpRequest":
        response_data = {
            "name": product.name,
            "price": str(product.price),
            "category": product.category.name,
            "discounted_price": str(product.get_discounted_price()),
            "description": product.description,
            "image": product.image.url,
            "product_url": product.get_absolute_url(),
        }
        print("json got " + product.name)
        return JsonResponse(response_data)

    return render(
        request,
        "shop/product/detail.html",
        {
            "product": product,
            "category": category,
            "images": images,
            "specifications": specifications,
            "cart_product_form": cart_product_form,
            "comments": comments,
            "comment_form": comment_form,
        },
    )


@csrf_exempt
@xframe_options_exempt
def search(request):
    query = request.GET.get("q")
    if query:
        query = escape(query)
        products = Product.objects.filter(
            Q(name__icontains=query)
            | Q(description__icontains=query)
            | Q(specifications__name__icontains=query)
            | Q(specifications__value__icontains=query)
        ).distinct()
    else:
        products = Product.objects.all()
    paginated_products = paginate_data(
        products, request, 12
    )  # Adjust '12' to the desired number of items per page

    return render(
        request, "shop/search.html", {"products": paginated_products, "query": query}
    )


def about_view(request):
    return render(request, "shop/others/about.html")


def contact_us(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            message = "your message is sent to us."
            return render(request, "shop/others/contact_us.html", {"message": message})
    else:
        form = ContactForm()

    return render(request, "shop/others/contact_us.html", {"form": form})

Shopp/templates/shop/base/css_links.html
{% load static %}

<link href="{% static "images/favicon.png" %}" rel="shortcut icon">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800" rel="stylesheet">


<!--====== Vendor Css ======-->
<link rel="stylesheet" href="{% static "css/vendor.css" %}">

<!--====== Utility-Spacing ======-->
<link rel="stylesheet" href="{% static "css/utility.css" %}">

<!--====== App ======-->
<link rel="stylesheet" href="{% static "css/app.css" %}">

<!--====== App ======-->
<link rel="stylesheet" href="{% static "css/custom.css" %}">

Shopp/templates/shop/base/footer.html
{% load i18n %}
{% load static %}

<footer>
    <div class="outer-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="outer-footer__content u-s-m-b-40">

                        <span class="outer-footer__content-title">Contact Us</span>
                        <div class="outer-footer__text-wrap"><i class="fas fa-home"></i>

                            <span>4247 Ashford Drive Virginia VA-20006 USA</span></div>
                        <div class="outer-footer__text-wrap"><i class="fas fa-phone-volume"></i>

                            <span>(+0) 900 901 904</span></div>
                        <div class="outer-footer__text-wrap"><i class="far fa-envelope"></i>

                            <span>contact@domain.com</span></div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="outer-footer__content u-s-m-b-40">

                                <span class="outer-footer__content-title">Information</span>
                                <div class="outer-footer__list-wrap">
                                    <ul>
                                        <li>

                                            <a href="{% url "cart:cart_detail" %}">Cart</a></li>
                                        <li>

                                            <a href="{% url 'accounts:user_dashboard' %}">Account</a></li>
                                        <li>
                                        <li>

                                            <a href="{% url "shop:product_list" %}">Shop</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="outer-footer__content u-s-m-b-40">
                                <div class="outer-footer__list-wrap">

                                    <span class="outer-footer__content-title">Our Company</span>
                                    <ul>
                                        <li>

                                            <a href="{% url 'shop:about' %}">About us</a></li>
                                        <li>

                                            <a href="{% url 'shop:contact' %}">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="lower-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="lower-footer__content">
                        <div class="lower-footer__copyright">

                            <span>Copyright © 2018</span>

                            <a href="index-2.html"><My shop></a>

                            <span>All Right Reserved</span></div>
                        <div class="lower-footer__payment">
                            <ul>
                                <li><i class="fab fa-cc-stripe"></i></li>
                                <li><i class="fab fa-cc-paypal"></i></li>
                                <li><i class="fab fa-cc-mastercard"></i></li>
                                <li><i class="fab fa-cc-visa"></i></li>
                                <li><i class="fab fa-cc-discover"></i></li>
                                <li><i class="fab fa-cc-amex"></i></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

Shopp/templates/shop/base/js_links.html
{% load static %}

<script src="https://www.google-analytics.com/analytics.js" async defer></script>

<!--====== Font Awesome ======-->
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>



<!--====== Vendor Js ======-->
<script src="{% static "js/vendor.js" %}"></script>

<!--====== jQuery Shopnav plugin ======-->
<script src="{% static "js/jquery.shopnav.js" %}"></script>

<!--====== App ======-->
<script src="{% static "js/app.js" %}"></script>

<!--====== custom ======-->
<script src="{% static "js/customJS.js" %}"></script>

<!--====== Noscript ======-->
<noscript>
    <div class="app-setting">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="app-setting__wrap">
                        <h1 class="app-setting__h1">JavaScript is disabled in your browser.</h1>

                        <span class="app-setting__text">Please enable JavaScript in your browser or upgrade to a JavaScript-capable browser.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</noscript>

Shopp/templates/shop/base/navbar.html
{% load i18n %}
{% load static %}


<header class="header--style-1">

    <!--====== Nav 1 ======-->
    <nav class="primary-nav primary-nav-wrapper--border">
        <div class="container">

            <!--====== Primary Nav ======-->
            <div class="primary-nav">

                <!--====== Main Logo ======-->

                <a class="main-logo" href="{% url "shop:product_list" %}">

                    <img src="{% static "images/logo/logo-1.png" %}" alt=""></a>
                <!--====== End - Main Logo ======-->


                <!--====== Search Form ======-->
                <form class="main-form" method="get" action="{% url 'shop:search' %}">

                    <label for="main-search"></label>

                    <input class="input-text input-text--border-radius input-text--style-1" type="text" id="main-search" placeholder="Search" name="q">

                    <button class="btn btn--icon fas fa-search main-search-button" type="submit"></button>
                        
                </form>
                <!--====== End - Search Form ======-->


                <!--====== Dropdown Main plugin ======-->
                <div class="menu-init" id="navigation">

                    <button class="btn btn--icon toggle-button toggle-button--secondary fas fa-cogs" type="button"></button>

                    <!--====== Menu ======-->
                    <div class="ah-lg-mode">

                        <span class="ah-close">✕ Close</span>

                        <!--====== List ======-->
                        <ul class="ah-list ah-list--design1 ah-list--link-color-secondary">
                            <li class="has-dropdown" data-tooltip="tooltip" data-placement="left" title="Account">

                                <a><i class="far fa-user-circle"></i></a>

                                <!--====== Dropdown ======-->

                                <span class="js-menu-toggle"></span>
                                <ul style="width:120px">
                                    {% if user.is_authenticated %}
                                    <li>

                                        <a href="{% url 'accounts:user_dashboard' %}"><i class="fas fa-user-circle u-s-m-r-6"></i>

                                            <span>Account</span></a>
                                    </li>
                                    <li>

                                        <a href="{% url 'accounts:logout' %}"><i class="fas fa-lock-open u-s-m-r-6"></i>

                                            <span>Sign Out</span></a>
                                    </li>
                                    {% else %}
                                    <li>

                                        <a href="{% url 'accounts:login' %}"><i class="fas fa-lock u-s-m-r-6"></i>

                                            <span>Sign In</span></a>
                                    </li>
                                    <li>

                                        <a href="{% url 'accounts:signup' %}"><i class="fas fa-user-plus u-s-m-r-6"></i>

                                            <span>Sign Up</span></a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </li>

                            <li data-tooltip="tooltip" data-placement="left" title="Contact">

                                <a href="tel:+0900901904"><i class="fas fa-phone-volume"></i></a>
                            </li>
                            <li data-tooltip="tooltip" data-placement="left" title="Mail">

                                <a href="mailto:contact@domain.com"><i class="far fa-envelope"></i></a>
                            </li>
                            <li data-tooltip="tooltip" data-placement="left" title="cart">
                                <div class="cart">
                                    <a href="{% url "cart:cart_detail" %}" style="color: gray;">
                                        <i class="fas fa-shopping-bag"></i>
                                    {% with total_items=cart|length %}
                                    {% if total_items > 0 %}
                                    {% trans "Your cart" %}:
                                    
                                        {% blocktrans with total=cart.get_total_price count items=total_items %}
                                            {{ items }} item, ${{ total }}
                                            {% plural %}
                                            {{ items }} items, ${{ total }}
                                        {% endblocktrans %}
                                   
                                    {% else %}
                                    {% trans "Your cart is empty." %}
                                    {% endif %}
                                    {% endwith %}
                                    </a>
                                </div>
                            </li>
                        </ul>
                        <!--====== End - List ======-->
                    </div>
                    <!--====== End - Menu ======-->
                </div>
                <!--====== End - Dropdown Main plugin ======-->
            </div>
            <!--====== End - Primary Nav ======-->
        </div>
    </nav>
    <!--====== End - Nav 1 ======-->

</header>